name: Snyk Scan using GitHub Actions
on:
  push:
    branches:
      - master
jobs:
  build:
    name: SCA scan using Snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: RunSnyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
